name: Java Workflow Car Build process

on: [push]

jobs:
  BuildJava:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Verify the Java Version
        run: java --version
        
      - name: test gradel there or not
        run: gradle
        
      - name: Build java code
        run: gradle build
        
      - run: ls ./build/libs
