name: Java Workflow Car Build process

on: [push]

jobs:
  BuildJava:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Verify the Java Version
        run: java --version
        
      - name: test gradel there or not
        run: gradle
        
      - name: Build java code
        run: gradle build
        
      - run: ls ./build/libs
      
      - name: Upload the file
        uses: actions/upload-artifact@v2
        with:
          name: CarsAPIJarCk
          path: ./build/libs/
          retention-day: 5

  Deploy_and_Test_application:
    runs-on: ubuntu-latest
    needs: BuildJava
    steps:      
      - name: Download the Artifact
        uses: actions/download-artifact@v2
        with:
          name: CarsAPIJarCk
          
      - name: Deploy file in the Background
        run: |
          ls -ltr
          pwd
          java -jar cars-api.jar &
          sleep 30
          
      - name: Curl Testing
        run: | 
          hostname -i
          curl http://localhost:5000/cars/1 | grep -i "Ford"
