name: Java testing Commands 

on: [push]

jobs:
  run-shell-command:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2
        
      - name: Check Java Version
        run: java -v
